apiVersion: dns.dnspolicies.io/v1alpha1
kind: DnsPolicy
metadata:
  name: dnspolicy-sample-identity-ops
spec:
  dryrun: true
  # TargetSelector defines which pods this policy applies to
  # The controller will compute a hash of these labels for efficient lookups
  subject:
    serviceAccount: osman
  # BlockList defines domain patterns that are blocked
  blockList:
    - "*.malicious-site.com"
    - "tracking.ads.net"
